language: c++
sudo: required
dist: trusty

addons: &addons
  apt:
    packages: &packages
      - libzmq3-dev
      - libzmq3
      - automake
      - libtool
      - libboost-dev

compiler:
  - gcc
  - clang

script:
  - bash ./.travis_build.sh

