language: c++

compiler:
  - gcc
  - clang

before_script:
  - sudo add-apt-repository ppa:chris-lea/zeromq -y
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libzmq5-dev libzmq5 automake libtool
  - pkg-config --modversion libzmq || true
  - pkg-config --modversion libzmq3 || true

script:
  - bash ./.travis_build.sh

