language: c++
sudo: required
dist: trusty

addons: &addons
  apt:
    packages: &packages
      - libzmq3-dev
      - libzmq3
      - automake
      - libtool
      - libboost1.55-all-dev
      - libcurl4-openssl-dev

compiler:
  - gcc
  - clang

script:
  - |
    pushd /tmp
    git clone https://github.com/Opendigitalradio/ka9q-fec.git
    cd ka9q-fec
    mkdir build
    cd build
    cmake ..
    make
    sudo make install
    popd
  - |
    ./bootstrap.sh
    ./configure --enable-input-prbs --enable-input-test --enable-input-udp --enable-output-raw
    make

